### ISSUE TITLE
Where might a Shiny app be useful in this template? 

### ISSUE THREAD

**Issue by cansavvy** [jhudsl/DaSL_Course_Template_Bookdown#240]
**Is your feature request related to a problem? Please describe.**
Related to comment in #219 
This is very much a nice to have and probably something we won't be able to get to for awhile. 

But we can think about it in the meantime.

**Comment by carriewright11** [comment]
> **Is your feature request related to a problem? Please describe.**
> Related to comment in #219
> This is very much a nice to have and probably something we won't be able to get to for awhile.
> 
> But we can think about it in the meantime.

agreed... maybe good for:
1) making Leanpub quizzes
2) making credits

**Comment by carriewright11** [comment]
for making credits I think this would could work really well. You can import a csv file (which could have our default credits) and then create a table like you would in excel or something:
https://www.tablesgenerator.com/html_tables 
html tables could be nice for having more flexibility for formatting but this also has markdown. Will also think about how this  would work for Leanpub
